### ISSUE TITLE
No compatible version found: asynquence-contrib

### ISSUE THREAD

**Issue by bidhan-a** [getify/asynquence#67] opened 2015-07-05 08:24 UTC
I'm using node version 0.12.5 and npm version 2.11.2 . Doesn't asynquence-contrib work with these versions anymore?

**Comment by getify** [comment] 2015-07-05 13:09
Yes it does. I have no idea why you'd be told "no compatible version found". Perhaps this is part of the npm3 changes?

**Comment by getify** [comment] 2015-07-06 04:57
Looks like a confirmed breakage... tracking here:

https://github.com/getify/You-Dont-Know-JS/issues/480

**Comment by gaganmurghai** [comment] 2015-08-22 14:09
Any ideas when will this issue be fixed?

**Comment by getify** [comment] 2015-08-22 14:51
i had hoped that npm would fix itself, but they apparently are unconcerned with the fact that they broke packages.

this situation will be fixed with upcoming releases of asynquence and asynquence-contrib, which should be happening in the next couple of days I hope.

**Comment by getify** [comment] 2015-08-22 15:02
Update: apparently [this](https://github.com/npm/npm/issues/8855#issuecomment-133712040)

**Comment by gaganmurghai** [comment] 2015-08-22 15:17
is this update available.. i tried to upgrade and then install asynquence-contrib, issue is still same?

**Comment by getify** [comment] 2015-08-22 15:19
i dunno, i haven't tried yet. wouldn't surprise me if it's still broken, since they don't seem to be showing much concern for the packages they broke.

did you verify you have the `2.13.1` version of npm? `npm --version`

**Comment by getify** [comment] 2015-08-22 15:21
the hack work-around is to manually pull asynquence and asynquence-contrib from github and "install" them into your node_modules directory... inside each one, make sure to then run `npm install`.

**Comment by gaganmurghai** [comment] 2015-08-22 15:25
i ran this command npm install npm@2.13.1 and then ran npm -v it still shows i am on 2.11.3 version. So i guess i will just manually install it.

**Comment by KenanY** [comment] 2015-08-22 15:30
`npm install asynquence-contrib` works fine for me with the latest stable release of `npm` (`2.14.0`).

**Comment by getify** [comment] 2015-08-22 17:57
@KenanY can you manually check the versions you get installed of asynquence and asynquence-contrib? As of this moment, I believe it should be 0.8.0 and 0.10.1-b, respectively.

**Comment by KenanY** [comment] 2015-08-22 18:00
@getify I get `asynquence@0.8.0` and `asynquence-contrib@0.10.1-a`. AFAICT, there is no `asynquence-contrib@0.10.1-b` in the registry at the moment.

**Comment by getify** [comment] 2015-08-22 18:11
I meant `a`... mistyped. thanks for the confirmation. :)

**Comment by carlorizzante** [comment] 2015-08-31 14:17
I had a similar issue. I couldn't install Asynquence-contrib on npm@2.11.3.

I had first to update npm: <code>$ sudo npm i npm -g</code>

And then you can run <code>$ npm i asynquence-contrib</code>

**Comment by getify** [comment] 2015-09-05 01:18
I believe this is fixed with the release of both asynquence @ 0.8.2 and asynquence-contrib @ 0.11.0. Please re-open if issues persist.

**Closed by getify** 2015-09-05 01:18 UTC
